[package]
name = "smb-server"
description = "rustsmb — high-performance SMB1/2/3 file server binary wiring transport, protocol and POSIX backend"
edition.workspace = true
version.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "rustsmb"
path = "src/main.rs"

[features]
default = ["lib"]
lib = ["smb-server-auth/lib"]
handrolled = ["smb-server-auth/handrolled"]

[dependencies]
async-trait.workspace = true
tokio.workspace = true
tokio-uring.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
clap.workspace = true
smb-server-proto = { path = "../smb-server-proto" }
smb-server-proto-smb2 = { path = "../smb-server-proto-smb2", version = "0.2.0" }
smb-server-proto-smb1 = { path = "../smb-server-proto-smb1", version = "0.2.0" }
smb-server-transport = { path = "../smb-server-transport", version = "0.2.0" }
smb-server-vfs = { path = "../smb-server-vfs", version = "0.2.0" }
smb-server-backend-posix = { path = "../smb-server-backend-posix", version = "0.2.0" }
smb-server-backend-shadow = { path = "../smb-server-backend-shadow" }
sambafied-shadow = { path = "../sambafied-shadow" }
smb-server-auth = { path = "../smb-server-auth", version = "0.2.0", default-features = false }
smb-server-handle-store = { path = "../smb-server-handle-store", version = "0.2.0" }
ms-ndr = "0.1.1"
inotify.workspace = true
futures-util.workspace = true
win-sd.workspace = true
if-addrs.workspace = true

[lints]
workspace = true

[dependencies.serde_json]
version = "1"

[dev-dependencies]
tempfile = "3"
